force-app/main/default/objects/CaseChild__c/CaseChild__c.object-meta.xml
<CustomObject>
    <label>CaseChild</label>
    <nameField>
        <label>CaseChild Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseChilds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseChild__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CaseChilds</relationshipLabel>
    <relationshipName>CaseChilds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseChild__c/fields/DateTimeFieldTest__c.field-meta.xml
<CustomField>
    <fullName>DateTimeFieldTest__c</fullName>
    <label>DateTimeFieldTest</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CaseChild__c/fields/NumberFieldTest__c.field-meta.xml
<CustomField>
    <fullName>NumberFieldTest__c</fullName>
    <label>NumberFieldTest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CaseChild__c/fields/TestFieldTest__c.field-meta.xml
<CustomField>
    <fullName>TestFieldTest__c</fullName>
    <label>TestFieldTest</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InitiateCaseValues.cls
public class InitiateCaseValues {

    //cette classe permet juste d'initialiser qq valeurs dans mon org pour la démo
    public static void initData(){
        Case case1 = new Case(Description='test 1');
        Case case2 = new Case(Description='test 2');
        insert (new List<Case>{case1,case2});
        Case caseUsed = case1;
        
        List<CaseChild__c> ccs = new List<CaseChild__c>();
        for(integer count=0;count<7;count++){
            if(count>3)caseUsed=case2;
            ccs.add(new CaseChild__c(
                Name='caseChild'+count
                ,DateTimeFieldTest__c=DateTime.newInstance(2021, 1, count, 0, 0, 0)
                ,NumberFieldTest__c=count,
                TestFieldTest__c=' test value'+count
                ,Case__c=caseUsed.Id)
            );
        }
        insert(ccs);
    }
    
}